title: Site

columns:
  - width: 1/2
    sections:
      information:
        type: fields
        fields:
          metadescription:
            label: Meta Description
            type: textarea
            buttons: false
            help: 
              en: This description is what appears in Google search.
          introtext:
            label: Landing Page Text
            type: textarea
            buttons: false
            max: 150
      coverimage:
        type: files
        label: Landing Page Images
        template: background-cover
        layout: cards
        help:
          One of them will be chosen at random with every vist.
  - width: 1/2
    sections:
      generals:
        label: Information
        type: pages
        template: info
        image: false
      events:
        type: pages
        search: true
        template: event
        sortBy: datestart asc
        info: '{{ page.datestart.toDate("Y") }}'
        image: false
        flip: true
